线性代数

In [ ]:
#考核作业3线性代数测试例子

In [1]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

创建一个矩阵

In [3]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

矩阵的索引

In [4]:
x[3]

tensor(3)

In [ ]:
矩阵的长度

In [5]:
len(x)

4

In [ ]:
矩阵的张量

In [6]:
x.shape

torch.Size([4])

In [ ]:
创建一个5x4的矩阵

In [9]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵

In [11]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

更多轴的矩阵

In [13]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

相加

In [15]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #分配了一个新的内存，把A的一个副本给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

哈达玛积

In [16]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X ,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

求和

In [18]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

任意形状张量的元素和

In [27]:
A=torch.arange(2*20,dtype=torch.float32).reshape(2，5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [32]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

指定求和汇总张量的轴

In [33]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [34]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

求均值

In [35]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [36]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [37]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播机制将A除以sum_A

In [38]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

某个轴计算A 元素的累积总和

In [39]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

点积

In [41]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

按元素乘法，再求和

In [43]:
torch.sum(x*y)

tensor(6.)

向量积

In [44]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵乘法

In [45]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根

In [47]:
u=torch.tensor([3.0,-4.0])
u,torch.norm(u)

(tensor([ 3., -4.]), tensor(5.))

L1范数，表示向量元素的绝对值之和

In [48]:
torch.abs(u).sum()

tensor(7.)

f范数是矩阵元素平方和的平方根

In [49]:
torch.norm(torch.ones((4,9)))

tensor(6.)