In [ ]:
#考核作业4自动求导测试例子

In [2]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

计算y关于x的梯度之前，需要一个地方来存储梯度

In [3]:
x.requires_grad_(True)
x.grad

In [1]:
y=2*torch.dot(x,x)
y

NameError: name 'torch' is not defined

调用反向传播函数来自动计算y关于x每个分量的梯度

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==4*x

tensor([True, True, True, True])

计算x的另一个函数

In [12]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

每个样本单独计算的偏导数之和

In [14]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [15]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [16]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [ ]:
#即使构建函数的计算图需要通过Python控制流(例如，条件，循环或任意函数调用)，我们依然可以计算得到变量的梯度

In [18]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c
a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
a.grad==d/a

tensor(True)