In [ ]:
1-2.深度学习的应用
用于图片分类、物体检测和分割、样式迁移、人脸合成、文字生成图片、文字生成、无人驾驶等等
案例研究
深度学习简单步骤：特征提取->模型预测



6-1数据操作
N维数组：机器学习和神经网络的主要数据结构
0-d(标量)——类别
1-d(向量)——特征向量
2-d(矩阵)——样本(特征矩阵)
3-d——RGB图片
4-d——RGB图片批量
5-d——RGB视频批量

7.2数据操作

In [2]:
#创建数组
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
print(x.shape,x.numel())
x=x.reshape(3,4)
x                          

torch.Size([12]) 12


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [3]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [4]:
torch.ones(3,4,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [16]:
#嵌套列表对元素赋值
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
#常见的标准算术运算符
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [5]:
#连接多个量  cat
x=torch.arange(12,dtype=torch.float32).reshape((3,4))  #使用arange()方法创建等差数组
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0) ,torch.cat((x,y),dim=1)  # #按列方向进行连接,按行方向进行连接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [43]:
#使用逻辑运算符构建张量
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [44]:
x.sum()  #对张量求和结果是标量

tensor(66.)

In [45]:
#调用广播机制执行元素操作
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b,a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [46]:
#索引的使用权限
#1.访问元素
x[1,2]=6
x,x[-1],x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [47]:
#2.写入、修改元素
x[1,2]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
#修改多个赋值
x[0:2,:]=12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [52]:
X=torch.tensor([1,2,3])
Y=torch.tensor([1,2,2])
before=id(Y)  #id指针的意义
Y=X+Y   #结果重新分配内存,注意X=X+Y不等与X+=Y
id(Y)==before

False

In [59]:
#执行原地操作
Z=torch.zeros_like(Y)
print("id(Z):",id(Z))
#原地修改方法1
Z[:]=X+Y
print("id(Z):",id(Z))
#原地修改方法2
before=id(X)
X+=Y
id(X)==before  #注意==用于判断,而=用于赋值

id(Z): 2224580555104
id(Z): 2224580555104


True

In [61]:
A=x.numpy()   #转换为Numpy
B=torch.tensor(A)
type(A),type(B) #打印存储类型

(numpy.ndarray, torch.Tensor)

In [64]:
#将大小为1的张量转换为python标量
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)
#a.item()表示numpy的浮点数

(tensor([3.5000]), 3.5, 3.5, 3)

8.3数据预处理

In [8]:
#创建人工数据集，存储在csv文件
import os
os.makedirs(os.path.join('data'),exist_ok=True)
data_file=os.path.join('house_tiny.csv')
#原本是join('..','house....),在上级目录（..）创建 data 文件夹
with  open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')#列名
    f.write('NA,Pave,127500\n')  #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [24]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [41]:
#处理缺失数据(插值、删除）
inputs,outputs=data.iloc[:,0:1],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())   #对缺失值插入该列的平均值
inputs,outputs

(   NumRooms
 0       3.0
 1       2.0
 2       4.0
 3       3.0,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [42]:
#将inputs中类别值，离散值归类
inputs=pd.get_dummies(data,dummy_na=True)
print(inputs)

   NumRooms   Price  Alley_Pave  Alley_nan
0       NaN  127500        True      False
1       2.0  106000       False       True
2       4.0  178100       False       True
3       NaN  140000       False       True


In [45]:
#将inputs和outputs所有转换为张量格式

x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3.],
         [2.],
         [4.],
         [3.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [44]:
print(inputs.dtypes)
print(outputs.dtypes)
import pandas as pd
import torch

# 先处理 inputs
inputs = inputs.apply(pd.to_numeric, errors='coerce')
# 再次填充可能产生的新缺失值
inputs = inputs.fillna(inputs.mean())

# 同样处理 outputs（如果它也有非数值类型）
outputs = outputs.apply(pd.to_numeric, errors='coerce')
outputs = outputs.fillna(outputs.mean())

# 现在再转换为张量
x = torch.tensor(inputs.values.astype(float), dtype=torch.float32)
y = torch.tensor(outputs.values.astype(float), dtype=torch.float32)
# 先分离输入和输出
inputs = data.iloc[:, :1]  # 假设第一列是 NumRooms
outputs = data.iloc[:, 2]   # 假设第三列是 Price

# 处理 inputs 的缺失值
inputs = inputs.fillna(inputs.mean())

# 对 inputs 中的类别列进行独热编码（如果 inputs 里有类别列的话）
# 例如，如果 inputs 包含 'Alley' 列：
# inputs = pd.get_dummies(inputs, dummy_na=True)

# 处理 outputs 的缺失值
outputs = outputs.fillna(outputs.mean())

# 最后转换为张量
x = torch.tensor(inputs.values.astype(float), dtype=torch.float32)
y = torch.tensor(outputs.values.astype(float), dtype=torch.float32)

NumRooms      float64
Price           int64
Alley_Pave       bool
Alley_nan        bool
dtype: object
int64


9-4问题回答

In [4]:
#reshape不改变地址
import torch
A=torch.arange(12)
B=A.reshape((3,4))
B
B[:]=2  #reshape不改变地址所以A被改变
A

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

pytorch与numpy的区别
reshape和vive

10-1线性代数
11-2线性代数实现

In [46]:
import torch 
#标量
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y  #基本计算

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [48]:
#向量（视为标量组成的列表）
x=torch.arange(4)
x,x[3]  #张量的索引访问元素

(tensor([0, 1, 2, 3]), tensor(3))

In [49]:
len(x)  ,x.shape  #访问张量长度和形状

(4, torch.Size([4]))

In [51]:
#使用两个分量可创建矩阵
A=torch.arange(20).reshape(5,4)
A,A.T  #显示矩阵及其转置

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [53]:
#对称矩阵 A的转置等于本身
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B,B==B.T  

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [54]:
#向量是标量的推广，矩阵是向量的推广，因此，我们能够构建更多轴的数据结构。
x=torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [55]:
#两个相同形状的张量二元运算的结果均是相同形状的张量
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()  #分配新内存，将A的副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [56]:
#矩阵的乘积(哈达玛积）
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [57]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+A,(a*A).shape

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 torch.Size([5, 4]))

In [58]:
#求和
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [60]:
A=torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum()   #对所有元素求和

(torch.Size([2, 5, 4]), tensor(780))

In [63]:
#对指定轴求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
A_sum_axis0,A_sum_axis0.shape,A_sum_axis1,A_sum_axis1.shape,A.sum(axis=[0,1])

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]),
 tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]),
 tensor([180, 190, 200, 210]))

In [71]:
#求平均值
A.mean(dtype=torch.float32), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [73]:
A.mean(axis=0,dtype=torch.float32), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [75]:
#计算总和或均值时轴数不变
sum_A=A.sum(axis=1,keepdims=True)
sum_A,A/sum_A   #后者利用广播将A/sum_A

(tensor([[[ 40,  45,  50,  55]],
 
         [[140, 145, 150, 155]]]),
 tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
          [0.1000, 0.1111, 0.1200, 0.1273],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.3000, 0.2889, 0.2800, 0.2727],
          [0.4000, 0.3778, 0.3600, 0.3455]],
 
         [[0.1429, 0.1448, 0.1467, 0.1484],
          [0.1714, 0.1724, 0.1733, 0.1742],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2286, 0.2276, 0.2267, 0.2258],
          [0.2571, 0.2552, 0.2533, 0.2516]]]))

In [76]:
#某轴累积总和
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

In [77]:
#点积：相同位置的元素乘积的和
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [78]:
#也可通过先进行元素乘法，再进行求和 表示点积
torch.sum(x*y)

tensor(6.)

In [80]:
A.shape,x.shape

(torch.Size([2, 5, 4]), torch.Size([4]))

In [85]:
#矩阵向量积计算
C=torch.arange(20).reshape(5,4).float()
C,C.shape,x.shape,torch.mv(C,x)   

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [86]:
#矩阵-矩阵乘法BC
C=torch.ones(4,3)
torch.mm(B,C)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [88]:
#范数：向量元素平方和的平方根
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [89]:
#L1范数：向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [90]:
#矩阵的佛罗贝尼乌斯范数：矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

12-3按特定轴求和

In [91]:
import torch
a=torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [97]:
a.sum().shape  #结果为空表示标量
a.sum(axis=1).shape,a.sum(axis=1),a.sum(axis=[0,1]),a.sum(axis=[0,1]).shape

(torch.Size([2, 4]),
 tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 tensor([10., 10., 10., 10.]),
 torch.Size([4]))

In [99]:
a.sum(axis=1,keepdims=True).shape,a.sum(axis=1,keepdims=True)

(torch.Size([2, 1, 4]),
 tensor([[[5., 5., 5., 5.]],
 
         [[5., 5., 5., 5.]]]))

17-2自动求导实现

In [22]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [23]:
#计算x的梯度之前，需要一个地方存放梯度
x.requires_grad_(True)   #等价于“x = torch.arange(4.0,requires_grad=True)
x.grad  #默认为None

In [24]:
y=2*torch.dot(x,x)   #计算y ,torch.dot(x, x) 表示两个一维张量的点积（内积
y

tensor(28., grad_fn=<MulBackward0>)

In [25]:
#调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()  #求导
x.grad  #访问导数

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad== 4*x  #验算求导结果是否正确

tensor([True, True, True, True])

In [15]:
#z在默认条件下，pytorch会累积梯度，需要手动清理
x.grad.zero_()  #将x梯度清零
#计算另外的函数
y=x.sum()
y.backward() #求导
x.grad

tensor([1., 1., 1., 1.])

需要批量中的每个样本单独计算的偏导数之和。
对非标量调用‘backward’需要传入‘grandient’参数，该参数指定微分函数

In [26]:
x.grad.zero_()  #将梯度清零
y = x * x
y.sum().backward() #等价于y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [28]:
#将某些计算移到计算图之外
x.grad.zero_()  #清零梯度
y=x*x
u=y.detach()  # 分离y得到u（u脱离计算图，视为常数）
z=u*x

z.sum().backward()   # 反向传播，计算z求和后对x的梯度
x.grad == u     #验证梯度结果

tensor([True, True, True, True])

In [29]:
x.grad.zero_()  #清零梯度
y.sum().backward()  # 反向传播，计算y求和后对x的梯度
x.grad==2*x

tensor([True, True, True, True])

In [33]:
#计算图需要复杂的python控制流的时候，依旧可以求导
def f(a):
    b = a *2
    while b.norm() < 1000:      # 循环：当b的范数小于1000时，持续将b翻倍
        b=b * 2
    if b.sum() >0:
        c=b
    else:
        c=100* b
    return c
a=torch.randn(size=(),requires_grad=True)
d=f(a)  # 前向传播计算d=f(a)
d.backward()  # 反向传播求d对a的梯度
a.grad == d/a  # 验证梯度：a.grad等于d/a（因d=k*a，导数为k=d/a）

tensor(True)