In [1]:
import torch

In [3]:
#生成一个从0-11的向量
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
#shape访问张量的维度/形状
x.shape

torch.Size([12])

In [10]:
#元素总数
x.numel()

12

In [11]:
#reshape函数只改变张量形状，不改变元素数量和元素值
y=x.reshape(3,4)#3行4列
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
#元素全0
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
#元素全1
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
#特定赋值
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])#二维

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
#标准算术运算符,元素进行
a=torch.tensor([1.0,2,4,8])#浮点
b=torch.tensor([2,2,2,2])#整数
a+b,a-b,a*b,a/b,a**b#加，减，乘，除，平方

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [19]:
#cat连结
X=torch.arange(12,dtype=torch.float32).reshape((3,4))#指定浮点
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1) #0行，1列

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
#构建二维张量
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
#对所有元素进行求和
X.sum()

tensor(66.)

In [26]:
#广播机制
c=torch.arange(3).reshape((3,1))#3行1列
d=torch.arange(2).reshape((1,2))#1行2列
print(c)
print(d)
c+d

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
#访问元素
print(X)
X[-1]
X[1:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
#指定元素写入矩阵
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
#为新结果分配内存
before=id(Y)
Y=Y+X
id(Y)==before

False

In [32]:
#执行原地操作
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 1712698143312
id(Z): 1712698143312


In [33]:
#减少操作的内存开销
before=id(X)
X+=Y
id(X)==before

True

In [35]:
#转换为numpy张量
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
#将大小为1的张量转换为python标量
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)