线性代数

In [1]:
import torch
#标量
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
#向量：标量组成的列表
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
#索引访问任一元素
x[3]

tensor(3)

In [5]:
#访问张量长度
print(len(x))
#形状
x.shape

4


torch.Size([4])

In [6]:
#创建矩阵
A=torch.arange(20).reshape(5,4)
print(A)
#转置
A.T

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
#对称矩阵--转置相同
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
B==B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [9]:
#矩阵是向量的推广,构建更多轴的数据结构
x=torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
#形状相同的任何两个张量，按元素二元运算的结果都将相同
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()#通过分配新内存将A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [18]:
#哈达玛积--乘法
print(A*B)
a=2
#常数乘矩阵
print(a*A)
#所有元素求和
A.sum()   #Asum(axis=[0,1])

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


tensor(190.)

In [17]:
#指定轴求和
print(A.reshape(2,2,5))
A.sum(axis=0),A.sum(axis=0).shape,A.sum(axis=1),A.sum(axis=1).shape

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]])


(tensor([40., 45., 50., 55.]),
 torch.Size([4]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [21]:
#均值
print(A.mean(),A.sum()/A.numel())
print(A.mean(axis=0),A.sum(axis=0)/A.shape[0])
#累加求和
print(A.cumsum(axis=0))

tensor(9.5000) tensor(9.5000)
tensor([ 8.,  9., 10., 11.]) tensor([ 8.,  9., 10., 11.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [26]:
#点积
a=torch.tensor([0.0,1.0,2.0,3.0])
b=torch.ones(4,dtype=torch.float32)
print(a,b,torch.dot(a,b))
#按元素乘法再求和
print(torch.sum(a*b))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor(6.)


In [29]:
B=torch.ones(4,3)
print(A,B,a)
#矩阵向量积
print(torch.mv(A,a))
#矩阵-矩阵乘法
print(torch.mm(A,B))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([0., 1., 2., 3.])
tensor([ 14.,  38.,  62.,  86., 110.])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [30]:
#范式--长度
u=torch.tensor([3.0,-4.0])
print(torch.norm(u))
#L1范数
print(torch.abs(u).sum())
#菲罗贝尼乌斯范数
print(torch.norm(torch.ones((4,9))))

tensor(5.)
tensor(7.)
tensor(6.)


矩阵计算

自动求导

In [31]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [33]:
#计算y关于x的梯度
#先存储梯度
x.requires_grad_(True)   #等价于x=torch.arange(4.0,requires_grad=True)
x.grad              #默认值是None
y=2*torch.dot(x,x)   #计算y
y

tensor(28., grad_fn=<MulBackward0>)

In [34]:
#反向传播函数
y.backward()#求导
x.grad

tensor([ 0.,  4.,  8., 12.])

In [35]:
x.grad==4*x#验证

tensor([True, True, True, True])

In [38]:
#默认情况下PyTorch会累积梯度，需要清除之前的值
x.grad.zero_()  #_表示重写之前的内容，zero表示把所有梯度清零#注释这行，运行结果变为[2,2,2,2]
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [39]:
#非标量调用backward需要传入一个gradint参数
x.grad.zero_()
y=x*x
#等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [40]:
x.grad.zero_()
y=x*x
u=y.detach()  #常数
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [41]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [ ]:
#构建函数的计算图需要通过python控制流
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()