In [1]:
import torch

In [2]:
#标量
x = torch.tensor(3.0)
y = torch.tensor(4.0)

x+y , x*y , x/y , x**y

(tensor(7.), tensor(12.), tensor(0.7500), tensor(81.))

In [7]:
#向量
x = torch.arange(5)
print(x)
x[3],x[4],x[-1]

tensor([0, 1, 2, 3, 4])


(tensor(3), tensor(4), tensor(4))

In [8]:
print(len(x))  #
x.shape        #列出每个轴的长度

5


torch.Size([5])

In [15]:
#矩阵
Z = torch.arange(12).reshape((3,4))
print(len(z))
Z.shape

3


torch.Size([3, 4])

In [16]:
Z.T  #Z的转置

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [17]:
#对称矩阵（A的转置等于A，即对称元素相等
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
#张量
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [19]:
#张量算法的基本性质
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()  #通过分配新内存，将A的一个副本分配给B
A , A+B        #具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [21]:
A * B  #逐元素乘法（两个矩阵的按元素乘法称为Hadamard积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [26]:
C = torch.arange(9).reshape(3,3)
D = torch.tensor([[1],[2],[3]])
C,D

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[1],
         [2],
         [3]]))

In [28]:
print(C @ D)  #矩阵乘法(一行乘一列再求和
torch.mm(C,D)  #二维矩阵 ， 任意维度使用torch.matmul() == @

tensor([[ 8],
        [26],
        [44]])


tensor([[ 8],
        [26],
        [44]])

In [29]:
#张量乘以或加上一个标量不会改变张量的形状
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [34]:
#降维（使用sum()函数
x = torch.arange(4,dtype=torch.float32)
x ,x.sum(), x.shape   #向量中元素的总和（将向量降维至一个标量

(tensor([0., 1., 2., 3.]), tensor(6.), torch.Size([4]))

In [35]:
#指定张量沿特定轴来通过求和降低维度
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [36]:
A_sum_axis0 = A.sum(axis=0)  #矩阵沿0轴降维（求和所有行的元素（垂直方向）
A_sum_axis0 , A_sum_axis0.shape  #长度为列数的长度

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [37]:
A_sum_axis1 = A.sum(axis=1)  #矩阵沿1轴降维（求和所有列的元素（水平方向）
A_sum_axis1 , A_sum_axis1.shape  #长度为行数的长度

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [38]:
A.sum(axis=[0,1])  #对多个轴进行求和

tensor(190.)

In [39]:
#求平均值
A.mean() , A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [40]:
#指定轴求平均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [42]:
#非降维求和
sum_A = A.sum(axis=0,keepdims=True)
sum_A

tensor([[40., 45., 50., 55.]])

In [45]:
A/sum_A  #利用广播机制计算 每个元素除以它所在列的总和

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [46]:
A.cumsum(axis=0)  #按行计算元素累积总和，不降低张量维度

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [47]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [48]:
#向量点积（相同位置按元素乘积的和，
y = torch.ones(4,dtype = torch.float32)
x , y , torch.dot (x,y)  #点积可使用逐行按元素相乘后求和等到（torcch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [57]:
#矩阵-向量积（A的列维数必须与x的维数相同
print(A,x)
A.shape, x.shape, torch.mv(A,x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([0., 1., 2., 3.])


(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [63]:
#范数（表示一个向量有多大,优化问题
u = torch.tensor([3.0,-4.0])
torch.norm(u)   #L2范数，所有元素平方和的平方根

tensor(5.)

In [64]:
torch.abs(u).sum()  #L1范数，所有元素绝对值的和

tensor(7.)

In [65]:
torch.norm(torch.ones((4,9)))  #Frobenius范数Lp（矩阵的L2范数

tensor(6.)

In [74]:
#练习
Q = torch.arange(24.0).reshape(2,3,4)  #torch.randn(2,3,4)
Q

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [75]:
Q.sum(axis=0),Q.sum(axis=1),Q.sum(axis=2)

(tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([[ 6., 22., 38.],
         [54., 70., 86.]]))

In [76]:
torch.linalg.norm(Q)

tensor(65.7571)