In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
#在计算y对x梯度之前，需要一个地方存储梯度
x.requires_grad_(True)  #等价于在创建x时加上requires_grad=True
x.grad

In [4]:
y = 2*torch.dot(x,x) #2||x||2 导数为2*2x
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
#调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4*x

tensor([True, True, True, True])

In [7]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
#向量y关于向量x的导数
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [10]:
#分离计算,分离y来返回一个新变量u,将u作为常数处理
x.grad.zero_()
y = x*x
u = y.detach()
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [13]:
def f(a):
    b = a*2
    while b.norm() <1000:
        b = b*2
    if b.sum()>0:
        c = b
    else:
        c = 100*b
    return c

In [14]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [15]:
a.grad == d / a

tensor(True)

In [16]:
y=x*x
y.sum().backward()
x.grad

tensor([ 0.,  4.,  8., 12.])